# Generated by Django 4.2.9 on 2024-01-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(max_length=255)),
                ('cell', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('nearest_infrastructure', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
    ]
