# Generated by Django 4.2.9 on 2024-01-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerceApp', '0002_alter_register_phone_number_alter_register_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_role',
            field=models.CharField(blank=True, default='user', max_length=255, null=True),
        ),
    ]
