# Generated by Django 4.2.9 on 2024-01-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerceApp', '0005_alter_register_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
            ],
        ),
    ]
