# Generated by Django 5.0 on 2024-01-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerceApp', '0007_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
